name: Hello World Workflow

on: [push]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Say Hello (locally)
        run: echo "Hello World!"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run tests
        run: npm test

      - name: Make run.sh executable
        run: chmod +x run.sh

      - name: Run the script locally
        run: ./run.sh

      - name: Upload run.sh to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "run.sh"
          target: "/home/${{ secrets.USERNAME }}/"

      - name: Execute run.sh on remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/${{ secrets.USERNAME }}
            chmod +x run.sh
            ./run.sh
