name: Hello World Workflow

on: [push]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Say Hello (locally)
        run: echo "Hello World!"

      - name: Show secret (still won't)
        run: echo $MY_SECRET
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}

      - name: Make run.sh executable
        run: chmod +x run.sh

      - name: Run the script locally
        run: ./run.sh

      - name: Upload run.sh to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "run.sh"
          target: "/home/${{ secrets.USERNAME }}/"

      - name: Execute run.sh on remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            chmod +x run.sh
            ./run.sh
