name: Hello World Workflow

on: [push]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "Hello World!"

      - name: Show secret (it won't)
        run: echo $MY_SECRET
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}

      - name: Run the script
        run: ./run.sh
