name: Hello World Workflow

on: [push]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Say Hello (locally)
        run: echo "Hello World!"

      - name: Make run.sh executable
        run: chmod +x run.sh

      - name: Run the script locally
        run: ./run.sh

      - name: Upload run.sh to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "run.sh"
          target: "/home/${{ secrets.USERNAME }}/"
          timeout: 60
          script_stop: true
          ssh_disable_strict_host_key_checking: true

      - name: Execute run.sh on remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          timeout: 60
          script_stop: true
          ssh_disable_strict_host_key_checking: true
          script: |
            cd /home/${{ secrets.USERNAME }}
            chmod +x run.sh
            ./run.sh
